spring:
  cloud:
    config:
      username: admin
      password: admin
server:
  port: 8084
elastic-query-config:
  text-field: text

elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000

