server:
  port: 8888
logging:
  level:
    ROOT: info
    org.spring.framework.cloud.config: debug
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/blessedeffulgence/spring-cloud-config-server-repository
          username: blessedeffulgence
          password: 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
          clone-on-start: false
      fail-fast: true
  security:
    user:
      name: admin
      password: admin
